image: eclipse-temurin:17-jdk

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository
    - target/

stages:
  - build
  - test

build-job:
  stage: build
  script:
    # Install dependencies
    - apt-get update && apt-get install -y wget unzip
    # Download and extract JavaFX SDK
    - wget https://download2.gluonhq.com/openjfx/22/openjfx-22_linux-x64_bin-sdk.zip
    - unzip openjfx-22_linux-x64_bin-sdk.zip -d /opt
    - export PATH_TO_FX=/opt/javafx-sdk-22/lib
    
    # Build the project with JavaFX modules
    - mvn compile -B
  artifacts:
    paths:
      - target/

test-job:
  stage: test
  script:
    # Install dependencies including xvfb for headless JavaFX tests
    - apt-get update && apt-get install -y wget unzip xvfb
    # Download and extract JavaFX SDK
    - wget https://download2.gluonhq.com/openjfx/22/openjfx-22_linux-x64_bin-sdk.zip
    - unzip openjfx-22_linux-x64_bin-sdk.zip -d /opt
    - export PATH_TO_FX=/opt/javafx-sdk-22/lib
    
    # Run tests with virtual display for JavaFX
    - xvfb-run mvn test -B
  dependencies:
    - build-job